---
name: "StyLua"
# yamllint disable-line rule:truthy
on:
  - push
  - pull_request
jobs:
  format_check:
    name: Run stylua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check lua format
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
