---
name: "Lint and format yaml code"
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
jobs:
  format_check:
    name: Run yamlfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - name: Run yamlfmt
        uses: yamlfmt -lint .
  lint_code:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
